basePath: /api/v1
info:
  contact: {}
  description: This is HireMeMaybe API service that provide data for HireMeMaybe web
    app
  title: HireMeMaybe API service
  version: "1.0"
paths: {}
swagger: "2.0"
