// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/google/callback": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Retrieves a query parameter named \"code\" from the request and returns it in a JSON response",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication code from google",
                        "name": "Code",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_auth.code"
                        }
                    }
                }
            }
        },
        "/auth/google/company": {
            "post": {
                "description": "Checks and creates user in the database, generates an access token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Handles Google login authentication for company role, exchanges code for user",
                "parameters": [
                    {
                        "description": "Authentication code from google",
                        "name": "Code",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth.code"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login success",
                        "schema": {
                            "$ref": "#/definitions/internal_auth.companyResponse"
                        }
                    },
                    "201": {
                        "description": "Register success",
                        "schema": {
                            "$ref": "#/definitions/internal_auth.companyResponse"
                        }
                    },
                    "400": {
                        "description": "Fail to receive token or fetch user info",
                        "schema": {
                            "$ref": "#/definitions/HireMeMaybe-backend_internal_utilities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Database error",
                        "schema": {
                            "$ref": "#/definitions/HireMeMaybe-backend_internal_utilities.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/google/cpsk": {
            "post": {
                "description": "Checks and creates user in the database, generates an access token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Handles Google login authentication for cpsk role, exchanges code for user",
                "parameters": [
                    {
                        "description": "Authentication code from google",
                        "name": "Code",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth.code"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login success",
                        "schema": {
                            "$ref": "#/definitions/internal_auth.cpskResponse"
                        }
                    },
                    "201": {
                        "description": "Register success",
                        "schema": {
                            "$ref": "#/definitions/internal_auth.cpskResponse"
                        }
                    },
                    "400": {
                        "description": "Fail to receive token or fetch user info",
                        "schema": {
                            "$ref": "#/definitions/HireMeMaybe-backend_internal_utilities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Database error",
                        "schema": {
                            "$ref": "#/definitions/HireMeMaybe-backend_internal_utilities.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Username must exist and password match",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Handles local login by receiving username and password",
                "parameters": [
                    {
                        "description": "Credentials for login",
                        "name": "Info",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth.loginInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "If role is cpsk",
                        "schema": {
                            "$ref": "#/definitions/internal_auth.cpskResponse"
                        }
                    },
                    "400": {
                        "description": "Info provided not met the condition",
                        "schema": {
                            "$ref": "#/definitions/HireMeMaybe-backend_internal_utilities.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Username not exist or password incorrect",
                        "schema": {
                            "$ref": "#/definitions/HireMeMaybe-backend_internal_utilities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Database or password hashing error",
                        "schema": {
                            "$ref": "#/definitions/HireMeMaybe-backend_internal_utilities.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Username must not already exist and password must longer or equal to 8 characters long",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Handles local registration by receiving username and password",
                "parameters": [
                    {
                        "description": "role can be only 'cpsk' or 'company'",
                        "name": "Info",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth.registerInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "If role is cpsk",
                        "schema": {
                            "$ref": "#/definitions/internal_auth.cpskResponse"
                        }
                    },
                    "400": {
                        "description": "Info provided not met the condition",
                        "schema": {
                            "$ref": "#/definitions/HireMeMaybe-backend_internal_utilities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Database or password hashing error",
                        "schema": {
                            "$ref": "#/definitions/HireMeMaybe-backend_internal_utilities.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "HireMeMaybe-backend_internal_model.Application": {
            "type": "object",
            "required": [
                "post_id",
                "resume_id"
            ],
            "properties": {
                "answer": {
                    "$ref": "#/definitions/HireMeMaybe-backend_internal_model.ApplicationAnswer"
                },
                "answer_id": {
                    "type": "integer"
                },
                "applied_at": {
                    "type": "string"
                },
                "cpsk_id": {
                    "description": "CPSKID references CPSKUser.UserID (uuid)",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "post_id": {
                    "description": "PostID references JobPost.ID",
                    "type": "integer"
                },
                "resume_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "HireMeMaybe-backend_internal_model.ApplicationAnswer": {
            "type": "object",
            "properties": {
                "expected_salary": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "programming_languages": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "right_to_work": {
                    "type": "string"
                },
                "year_of_experience": {
                    "type": "integer"
                }
            }
        },
        "HireMeMaybe-backend_internal_model.CPSKUser": {
            "type": "object",
            "properties": {
                "applications": {
                    "description": "List of job applications made by the CPSK user",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/HireMeMaybe-backend_internal_model.Application"
                    }
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "program": {
                    "type": "string"
                },
                "resume_id": {
                    "type": "integer"
                },
                "soft_skill": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "user": {
                    "$ref": "#/definitions/HireMeMaybe-backend_internal_model.User"
                },
                "year": {
                    "type": "string"
                }
            }
        },
        "HireMeMaybe-backend_internal_model.Company": {
            "type": "object",
            "properties": {
                "banner_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "industry": {
                    "type": "string"
                },
                "job_post": {
                    "description": "JobPost holds the company's job posts",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/HireMeMaybe-backend_internal_model.JobPost"
                    }
                },
                "logo_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "overview": {
                    "type": "string"
                },
                "size": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/HireMeMaybe-backend_internal_model.User"
                },
                "verified_status": {
                    "type": "string"
                }
            }
        },
        "HireMeMaybe-backend_internal_model.JobPost": {
            "type": "object",
            "properties": {
                "applications": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/HireMeMaybe-backend_internal_model.Application"
                    }
                },
                "company_id": {
                    "type": "string"
                },
                "desc": {
                    "type": "string"
                },
                "exp_lvl": {
                    "type": "string"
                },
                "expiring": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "post_time": {
                    "type": "string"
                },
                "req": {
                    "type": "string"
                },
                "salary": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "HireMeMaybe-backend_internal_model.User": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "profile_picture": {
                    "type": "string"
                },
                "tel": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "HireMeMaybe-backend_internal_utilities.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "internal_auth.code": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                }
            }
        },
        "internal_auth.companyResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/HireMeMaybe-backend_internal_model.Company"
                }
            }
        },
        "internal_auth.cpskResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/HireMeMaybe-backend_internal_model.CPSKUser"
                }
            }
        },
        "internal_auth.loginInfo": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_auth.registerInfo": {
            "type": "object",
            "required": [
                "password",
                "role",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "cpsk",
                        "company"
                    ]
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "HireMeMaybe API service",
	Description:      "This is HireMeMaybe API service that provide data for HireMeMaybe web app",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
