basePath: /api/v1
definitions:
  HireMeMaybe-backend_internal_model.Application:
    properties:
      answer:
        $ref: '#/definitions/HireMeMaybe-backend_internal_model.ApplicationAnswer'
      answer_id:
        type: integer
      applied_at:
        type: string
      cpsk_id:
        description: CPSKID references CPSKUser.UserID (uuid)
        type: string
      id:
        type: integer
      post_id:
        description: PostID references JobPost.ID
        type: integer
      resume_id:
        type: integer
      status:
        type: string
    required:
    - post_id
    - resume_id
    type: object
  HireMeMaybe-backend_internal_model.ApplicationAnswer:
    properties:
      expected_salary:
        type: string
      id:
        type: integer
      programming_languages:
        items:
          type: string
        type: array
      right_to_work:
        type: string
      year_of_experience:
        type: integer
    type: object
  HireMeMaybe-backend_internal_model.CPSKUser:
    properties:
      applications:
        description: List of job applications made by the CPSK user
        items:
          $ref: '#/definitions/HireMeMaybe-backend_internal_model.Application'
        type: array
      first_name:
        type: string
      id:
        type: string
      last_name:
        type: string
      program:
        type: string
      resume_id:
        type: integer
      soft_skill:
        items:
          type: string
        type: array
      user:
        $ref: '#/definitions/HireMeMaybe-backend_internal_model.User'
      year:
        type: string
    type: object
  HireMeMaybe-backend_internal_model.User:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      email:
        type: string
      id:
        type: string
      profile_picture:
        type: string
      tel:
        type: string
      updatedAt:
        type: string
      username:
        type: string
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  internal_auth.CPSKResponse:
    properties:
      access_token:
        type: string
      user:
        $ref: '#/definitions/HireMeMaybe-backend_internal_model.CPSKUser'
    type: object
  internal_auth.Code:
    properties:
      code:
        type: string
    required:
    - code
    type: object
  internal_auth.ErrorResponse:
    properties:
      error:
        type: string
    type: object
info:
  contact: {}
  description: This is HireMeMaybe API service that provide data for HireMeMaybe web
    app
  title: HireMeMaybe API service
  version: "1.0"
paths:
  /google/cpsk:
    post:
      consumes:
      - application/json
      description: Checks and creates user in the database, generates an access token
      parameters:
      - description: Authentication code from google
        in: body
        name: code
        required: true
        schema:
          $ref: '#/definitions/internal_auth.Code'
      produces:
      - application/json
      responses:
        "200":
          description: Login
          schema:
            $ref: '#/definitions/internal_auth.CPSKResponse'
        "201":
          description: Register
          schema:
            $ref: '#/definitions/internal_auth.CPSKResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_auth.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_auth.ErrorResponse'
      summary: Handles Google login authentication for cpsk role, exchanges code for
        user
      tags:
      - auth
swagger: "2.0"
