name: golangci-lint
on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod

permissions:
  contents: read
  # Optional: allow read access to pull requests. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: v1.24
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1